crashlyticsApiKey=ffffffffffffffffffffffffffffffffffffffff

# PSPDFKit
pspdfMavenUser=pspdfkit
pspdfMavenPass=jZdwMw7uqYGuKc6RxYLuEPwYqyvYQQ
pspdfkitLicenseKey=

heapProductionId=0123456789
heapStagingId=0123456789

# Pronoun Test Student User
pronounTestStudent=1
pronounTestStudentPassword=2

# Student User for Push Notifications
pushNotificationsTestStudent=3
pushNotificationsTestStudentPassword=4

# Pendo
pendoAccessToken=1
