fabricApiKey=1
versioneye.api_key=1
versioneye.projectid=1

# Robo Testing - Canvas Teacher
roboTestUserToken=1
roboTestDomain=1
roboUser=1

# PSPDFKit
pspdfMavenUser=pspdfkit
pspdfMavenPass=jZdwMw7uqYGuKc6RxYLuEPwYqyvYQQ
pspdfkitLicenseKey=

heapProductionId=0123456789
heapStagingId=0123456789

# Pronoun Test Teacher User
pronounTestTeacher=1
pronounTestTeacherPassword=2

# Teacher User for Push Notifications
pushNotificationsTestTeacher=3
pushNotificationsTestTeacherPassword=4

# Pendo
pendoAccessToken=1
